# Generated by Django 4.0.1 on 2022-01-21 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
