# Generated by Django 4.0.1 on 2022-01-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='phone number starts from +(your code)xxx-xxx-xx', max_length=12, unique=True, verbose_name='Phone'),
        ),
    ]
